name: Garnet Security Monitoring

on:
  push:
    branches: ["main"]

jobs:
  test_app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: npm install
      - run: node index.js
      - uses: garnet-org/action@v1
        continue-on-error: true
        with:
          api_token: ${{ secrets.GARNET_API_TOKEN }}

  behavior_heavy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: node behavior_heavy.js
      - uses: garnet-org/action@v1
        continue-on-error: true
        with:
          api_token: ${{ secrets.GARNET_API_TOKEN }}

  file_spray:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: node file_spray.js
      - uses: garnet-org/action@v1
        continue-on-error: true
        with:
          api_token: ${{ secrets.GARNET_API_TOKEN }}

  network_domains:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: node network_domains.js
      - uses: garnet-org/action@v1
        continue-on-error: true
        with:
          api_token: ${{ secrets.GARNET_API_TOKEN }}

  dns_tunnel_sim:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: node dns_tunnel_sim.js
      - uses: garnet-org/action@v1
        continue-on-error: true
        with:
          api_token: ${{ secrets.GARNET_API_TOKEN }}

  crypto_miner_sim:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: node crypto_miner_sim.js
      - uses: garnet-org/action@v1
        continue-on-error: true
        with:
          api_token: ${{ secrets.GARNET_API_TOKEN }}


