name: Garnet Security Monitoring

on:
  push:
    branches: ["main"]

jobs:
  test_app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - uses: garnet-org/action@v1
        continue-on-error: true
        with:
          api_token: ${{ secrets.GARNET_API_TOKEN }}
      - run: node index.js

  behavior_heavy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - uses: garnet-org/action@v1
        continue-on-error: true
        with:
          api_token: ${{ secrets.GARNET_API_TOKEN }}
      - run: node behavior_heavy.js

  file_spray:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - uses: garnet-org/action@v1
        continue-on-error: true
        with:
          api_token: ${{ secrets.GARNET_API_TOKEN }}
      - run: node file_spray.js

  network_domains:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - uses: garnet-org/action@v1
        continue-on-error: true
        with:
          api_token: ${{ secrets.GARNET_API_TOKEN }}
      - run: node network_domains.js

  dns_tunnel_sim:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - uses: garnet-org/action@v1
        continue-on-error: true
        with:
          api_token: ${{ secrets.GARNET_API_TOKEN }}
      - run: node dns_tunnel_sim.js

  crypto_miner_sim:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - uses: garnet-org/action@v1
        continue-on-error: true
        with:
          api_token: ${{ secrets.GARNET_API_TOKEN }}
      - run: node crypto_miner_sim.js

  chainstack_probe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - uses: garnet-org/action@v1
        continue-on-error: true
        with:
          api_token: ${{ secrets.GARNET_API_TOKEN }}
      - run: node chainstack_probe.js


